kontrapunkt/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    
    path('country_list/', views.CountryListView.as_view(), name='country_list'),
    path('country/<int:pk>', views.CountryDetailView.as_view(), name='country_detail'),
    path('country/create/', views.CountryCreate.as_view(), name='country_create'),
    path('country/<int:pk>/update/', views.CountryUpdate.as_view(), name='country_update'),
    path('country/<int:pk>/delete/', views.CountryDelete.as_view(), name='country_delete'),
    
#    path('country_list/', views.CountryListView.as_view(), name='country_list'),
    
    path('composer_list/', views.ComposerListView.as_view(), name='composer_list'),
    path('composer/<int:pk>', views.ComposerDetailView.as_view(), name='composer_detail'),
    path('composer/create/', views.ComposerCreate.as_view(), name='composer_create'),
    path('composer/<int:pk>/update/', views.ComposerUpdate.as_view(), name='composer_update'),
    path('composer/<int:pk>/delete/', views.ComposerDelete.as_view(), name='composer_delete'),
    
    path('composition_list/', views.CompositionListView.as_view(), name='composition_list'),
    path('composition/<int:pk>', views.CompositionDetailView.as_view(), name='composition_detail'),
    path('composition/create/', views.CompositionCreate.as_view(), name='composition_create'),
    path('composition/<int:pk>/update/', views.CompositionUpdate.as_view(), name='composition_update'),
    path('composition/<int:pk>/delete/', views.CompositionDelete.as_view(), name='composition_delete'),
    
]

kontrapunkt/kontrapunkt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from . import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

# Access to that directory
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kontrapunkt/catalog/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns

# def helper_datefield_to_year (datefield):
#     result = str(datefield)
#     if result=='' or result=='None':
#       return '-'
#     else:
#       return datefield.year

# def helper_datefield_to_text (datefield):
#     result = str(datefield)
#     if result=='' or result=='None':
#         result = '-'
#     return result

class Country(models.Model):
    name = models.CharField(max_length=100)
    flag = models.ImageField(upload_to='images/', null=True, blank=True, default='a000.png') # http://pluto.serverenmin.com:8000/media???? http://pluto.serverenmin.com:8000/media/%23
    def get_absolute_url(self):
        return reverse('country_detail', args=[str(self.id)])
    def __str__(self):
        return f'{self.name}'
#        return f'{self.name} <img src="0000"></img>' # As predicted: Plain text 

class Composer(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    year_of_birth = models.CharField(max_length=12, default='', help_text='Year as text') # E.g. "1732",  "1620-30", or "unknown"
    year_of_death = models.CharField(max_length=12, default='', help_text='Year as text') # E.g. "1732",  "1620-30", or "unknown"

#     date_of_birth = models.DateField(null=True, blank=True)
#     date_of_death = models.DateField('Died', null=True, blank=True)

    country = models.ForeignKey('Country', on_delete=models.SET_NULL, null=True)
#     class Meta:
#         ordering = ['last_name', 'first_name']
#     def get_year_information(self):
#         return self.get_birth_year
        
    def get_lifespan (self):
#        return f'{helper_datefield_to_year(self.date_of_birth)}-{helper_datefield_to_year(self.date_of_death)}'
        return f'{self.year_of_birth}-{self.year_of_death}'
        
#     def get_birth_text(self):
# #        return helper_datefield_to_text (self.date_of_birth)
#       return self.year_of_birth
#     def get_death_text(self):
# #        return helper_datefield_to_text (self.date_of_death)
#       return self.year_of_death

    def get_absolute_url(self):
        return reverse('composer_detail', args=[str(self.id)])
    def __str__(self):
#        return f'{self.last_name}, {self.first_name}, ({self.get_birth_text()})-({self.get_death_text()})'
        return f'{self.last_name}, {self.first_name}'
        
class CompositionCategory(models.Model):
    name = models.CharField(max_length=100) # E.g. symphony
    def __str__(self):
        return f'{self.name}'
        
class Composition(models.Model):
    name = models.CharField(max_length=100) # E.g. mass in D-minor
    summary = models.TextField(max_length=1000, help_text='Enter a brief description', blank=True, null=True)
    year = models.CharField(max_length=12, default='', help_text='Year as text') # E.g. "1732",  "1620-30", or "unknown"
    i_opus = models.IntegerField (default=0) # Opus number if >0
    i_category = models.IntegerField (default=0) # E.g. symphony number if >0
    composer = models.ForeignKey('Composer', on_delete=models.SET_NULL, null=True)
    compositioncategory = models.ForeignKey('CompositionCategory', on_delete=models.SET_NULL, null=True)
    def get_text_category (self):
      if (self.i_category>0):
        return f'{self.compositioncategory.name} no. {self.i_category}'
      else:
        return ''
    def get_text_opus (self):
      if (self.i_opus>0):
        return f'opus {self.i_opus}'
      else:
        return ''
    def get_absolute_url(self):
        return reverse('composition_detail', args=[str(self.id)])
    def get_text_without_composer(self):
        return f'{self.name} - {self.get_text_category()} {self.get_text_opus()} ({self.year})'
    def __str__(self):
        return f'{self.composer}: {self.name} - {self.get_text_category()} {self.get_text_opus()} ({self.year})'
#        return f'{self.get_text_without_composer} by {self.composer.name}'

class CollectionCategory(models.Model):
    name = models.CharField(max_length=100) # E.g. "lp", "cd", "flac_catalog", "concert", "tv_program", "kontrapunkt"
    def __str__(self):
        return f'{self.name}'

class Collection(models.Model):
    name = models.CharField(max_length=100) # E.g. kontrapunkt1988 0301, Vinylplate nr 88, Konsert Olavshallen 12 april 1993. KUN NAVN, INGEN KOBLINGER I DATABASEN
    summary = models.TextField(max_length=1000, help_text='Enter a brief description', blank=True, null=True)
    collectioncategory = models.ForeignKey('CollectionCategory', on_delete=models.SET_NULL, null=True)
    def get_absolute_url(self):
        return reverse('collection_detail', args=[str(self.id)])
    def __str__(self):
        return f'{self.name}'

class Piece(models.Model):
    name = models.CharField(max_length=100) # E.g. First movement
    composition = models.ForeignKey('Composition', on_delete=models.SET_NULL, null=True)
    i_sequence = models.IntegerField (default=0)
    def get_absolute_url(self):
        return reverse('piece_detail', args=[str(self.id)])
    def __str__(self):
        return f'{self.name}'

class PieceInstance(models.Model):
    comment = models.CharField(max_length=100, default="", blank=True, null=True) # E.g. "Very good performance"
    collection = models.ForeignKey('Collection', on_delete=models.SET_NULL, null=True)
    piece = models.ForeignKey('Piece', on_delete=models.SET_NULL, null=True)
    def get_absolute_url(self):
        return reverse('pieceinstance_detail', args=[str(self.id)])
    def __str__(self):
        return f'{self.name}'

kontrapunkt/catalog/views.py
from django.shortcuts import render
#from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views import generic


def index(request):
    """View function for home page of site."""

#     # Generate counts of some of the main objects
#     num_books = Book.objects.all().count()
#     num_instances = BookInstance.objects.all().count()
#     
#     # Available books (status = 'a')
#     num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    
    # The 'all()' is implied by default.    
    num_country = Country.objects.count()
    num_composer = Composer.objects.count()
    num_compositioncategory = CompositionCategory.objects.count()
    num_composition = Composition.objects.count()
    
#     # Number of visits to this view, as counted in the session variable.
#     num_visits = request.session.get('num_visits', 0)
#     request.session['num_visits'] = num_visits + 1

    context = {
#         'num_books': num_books,
#         'num_instances': num_instances,
#         'num_instances_available': num_instances_available,
        'num_country': num_country,
        'num_composer': num_composer,
        'num_compositioncategory': num_compositioncategory,
        'num_composition': num_composition,
#         'num_visits': num_visits,
    }    
    
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

# ===== Country =====
from catalog.models import Country

class CountryListView(generic.ListView):
    model = Country
#    paginate_by = 2
    
class CountryDetailView(generic.DetailView):
    model = Country    
    
class CountryCreate(generic.CreateView):
    model = Country
    fields = ['name', 'flag']
#    fields = '__all__'

class CountryUpdate(UpdateView):
    model = Country
    fields = '__all__'
#    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class CountryDelete(DeleteView):
    model = Country
    success_url = reverse_lazy('country_list')

# ===== Compositioncategory ===== 
from catalog.models import CompositionCategory

# ===== Composer =====
from catalog.models import Composer

class ComposerListView(generic.ListView):
    model = Composer
#    paginate_by = 2
    
class ComposerDetailView(generic.DetailView):
    model = Composer    
    
class ComposerCreate(generic.CreateView):
    model = Composer
    fields = '__all__'
#    initial = {'date_of_death': '05/01/2018'}

class ComposerUpdate(UpdateView):
    model = Composer
    fields = '__all__'
#    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class ComposerDelete(DeleteView):
    model = Composer
    success_url = reverse_lazy('composer_list')
    
# ===== Composition =====
from catalog.models import Composition

class CompositionListView(generic.ListView):
    model = Composition
#    paginate_by = 2
    
class CompositionDetailView(generic.DetailView):
    model = Composition    
    
class CompositionCreate(generic.CreateView):
    model = Composition
    fields = '__all__'
#    initial = {'date_of_death': '05/01/2018'}

class CompositionUpdate(UpdateView):
    model = Composition
    fields = '__all__'
#    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class CompositionDelete(DeleteView):
    model = Composition
    success_url = reverse_lazy('composition_list')
    

kontrapunkt/catalog/templates/catalog/composer_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete composer</h1>

<p>Are you sure you want to delete the composer: {{ composer }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

kontrapunkt/catalog/templates/catalog/composer_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ composer }} ({{ composer.get_lifespan }}) <img src="{{ composer.country.flag.url }}" width="1em" /></h1>

  <img src="{{ composer.flag.url }}" class="img-responsive" style="width: 80px; float: left; margin-right: 10px;" /> 
            
              
  <h3>Komposisjoner</h3>
  <hr>
    <ul>
  {% for copy in composer.composition_set.all %}
    <li><a href="{{ copy.get_absolute_url }}">{{ copy.get_text_without_composer }}</a></li>
  {% endfor %}
    </ul>
            

  <p><a href="{% url 'composer_update' composer.id %}">Update</a></p> 
  <p><a href="{% url 'composer_delete' composer.id %}">Delete</a></p> 

{% endblock %}

kontrapunkt/catalog/templates/catalog/composer_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

kontrapunkt/catalog/templates/catalog/composer_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Composer List</h1>
  {% if composer_list %}
  <ul>
    {% for composer in composer_list %}
      <li>
        <a href="{{ composer.get_absolute_url }}">{{ composer }} <img src="{{ composer.country.flag.url }}" width="20"> </img></a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no countries.</p>
  {% endif %}       
{% endblock %}

kontrapunkt/catalog/templates/catalog/composition_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete composition</h1>

<p>Are you sure you want to delete the composition: {{ composition }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

kontrapunkt/catalog/templates/catalog/composition_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ composition.name }}</h1>
  <div>{{ composition }}</div>
  <div>Name: {{ composition.name }}</div>
  <div>Summary: {{ composition.summary }}</div>
  <div>year: {{ composition.year }}</div>
  <div>opus: {{ composition.i_opus }}</div>
  <div>category: {{ composition.i_category }}</div>
  <div>Composer: {{ composition.composer }}</div>
  <div>Composition category: {{ composition.compositioncategory }}</div>

  <h3>Satser</h3>
  <hr>
    <ul>
  {% for copy in composition.piece_set.all %}
    <li>{{ copy }}</a></li>
  {% endfor %}
    </ul>


  <p><a href="{% url 'composition_update' composition.id %}">Update</a></p> 
  <p><a href="{% url 'composition_delete' composition.id %}">Delete</a></p> 

{% endblock %}

kontrapunkt/catalog/templates/catalog/composition_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

kontrapunkt/catalog/templates/catalog/composition_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Composition List</h1>
  {% if composition_list %}
  <ul>
    {% for composition in composition_list %}
      <li>
        <a href="{{ composition.get_absolute_url }}">{{ composition }} </img></a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no countries.</p>
  {% endif %}       
{% endblock %}

kontrapunkt/catalog/templates/catalog/country_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete country</h1>

<p>Are you sure you want to delete the country: {{ country }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

kontrapunkt/catalog/templates/catalog/country_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ country }}</h1>

  <img src="{{ country.flag.url }}" class="img-responsive" style="width: 80px; float: left; margin-right: 10px;" /> 
            
  <h3>Composers</h3>
  <hr>
  <ul>
  {% for copy in country.composer_set.all %}
    <li><a href="{{ copy.get_absolute_url }}">{{ copy }}</a></li>
  {% endfor %}
  </ul>



  <p><a href="{% url 'country_update' country.id %}">Update</a></p> 
  <p><a href="{% url 'country_delete' country.id %}">Delete</a></p> 

{% endblock %}

kontrapunkt/catalog/templates/catalog/country_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

kontrapunkt/catalog/templates/catalog/country_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Country List</h1>
  {% if country_list %}
  <ul>
    {% for country in country_list %}
      <li>
        
        <a href="{{ country.get_absolute_url }}"><img src="{{ country.flag.url }}" width="1em"></img> {{ country }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no countries.</p>
  {% endif %} 
  <hr>
  <a href="{% url 'country_create' %}">Create country</a>
  
        
{% endblock %}